BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "posts" (
	"id"	INTEGER NOT NULL UNIQUE,
	"type"	INTEGER NOT NULL,
	"city"	INTEGER NOT NULL,
	"url"	INTEGER NOT NULL UNIQUE,
	"floor"	INTEGER NOT NULL DEFAULT -1,
	"floorTotal"	INTEGER NOT NULL DEFAULT -1,
	"area"	INTEGER NOT NULL DEFAULT -1,
	"price"	INTEGER NOT NULL DEFAULT -1,
	"rooms"	INTEGER NOT NULL DEFAULT -1,
	"year"	INTEGER NOT NULL DEFAULT -1,
	"broker_fee"	INTEGER NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"conf_phase"	INTEGER NOT NULL DEFAULT -1,
	"type"	INTEGER NOT NULL DEFAULT -1,
	"city"	INTEGER NOT NULL,
	"enabled"	INTEGER NOT NULL DEFAULT -1,
	"price_from"	INTEGER NOT NULL DEFAULT -1,
	"price_to"	INTEGER NOT NULL DEFAULT -1,
	"rooms_from"	INTEGER NOT NULL DEFAULT -1,
	"rooms_to"	INTEGER NOT NULL DEFAULT -1,
	"year_from"	INTEGER NOT NULL DEFAULT -1,
	"year_to"	INTEGER NOT NULL DEFAULT -1,
	"broker_fee"	INTEGER NOT NULL DEFAULT -1,
	PRIMARY KEY("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "index_posts_type" ON "posts" (
	"type",
	"url"
);
COMMIT;
