version: "3.8"

services:
  bbtmvbot:
    container_name: bbtmvbot
    restart: unless-stopped
    build: .
    volumes:
      - ./telegram.conf:/app/telegram.conf
      - ./database.db:/app/database.db
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - "influxdb"
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - "./influxdb:/var/lib/influxdb"
    links:
      - "bbtmvbot"
      
